from pathlib import Path

from sqlalchemy import select
from sqlalchemy.orm import Session, selectinload
from starlette.concurrency import run_in_threadpool

from app.database.models import ExportRecord, Inspection
from app.services.excel.excel_exporter import generate_excel
from app.services.excel.template_manager import generate_word_report


async def async_export(inspection_id: str, format: str, db: Session) -> Path:
    inspection = db.scalar(
        select(Inspection)
        .options(selectinload(Inspection.images))
        .where(Inspection.id == inspection_id)
    )
    if inspection is None:
        raise ValueError("Inspection not found")

    export_format = format.lower()
    if export_format in {"excel", "xlsx"}:
        report_path = await run_in_threadpool(generate_excel, inspection)
        export_type = "excel"
    elif export_format in {"word", "docx", "photo_report"}:
        report_path = await run_in_threadpool(generate_word_report, inspection, None)
        export_type = "photo_report"
    else:
        raise ValueError(f"Unsupported export format: {format}")

    db.add(
        ExportRecord(
            inspection_id=inspection.id,
            export_type=export_type,
            filename=report_path.name,
            report_url=f"reports/{inspection.id}/{report_path.name}",
            email_sent=False,
            message="Export generated by background worker.",
        )
    )
    db.commit()
    return report_path
